
package com.godaddy.vps4.monitoring.iris.irisClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IrisWebServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IrisWebServiceSoap {


    /**
     * 
     * @param note
     * @param originalIPAddress
     * @param privateLabelID
     * @param createdBy
     * @param subject
     * @param customerEmailAddress
     * @param shopperID
     * @param groupID
     * @param subscriberID
     * @param serviceID
     * @return
     *     returns long
     */
    @WebMethod(operationName = "CreateIncidentInIRIS", action = "http://tempuri.org/CreateIncidentInIRIS")
    @WebResult(name = "CreateIncidentInIRISResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreateIncidentInIRIS", targetNamespace = "http://tempuri.org/", className = "irisClient.CreateIncidentInIRIS")
    @ResponseWrapper(localName = "CreateIncidentInIRISResponse", targetNamespace = "http://tempuri.org/", className = "irisClient.CreateIncidentInIRISResponse")
    public long createIncidentInIRIS(
        @WebParam(name = "subscriberID", targetNamespace = "http://tempuri.org/")
        int subscriberID,
        @WebParam(name = "subject", targetNamespace = "http://tempuri.org/")
        String subject,
        @WebParam(name = "Note", targetNamespace = "http://tempuri.org/")
        String note,
        @WebParam(name = "customerEmailAddress", targetNamespace = "http://tempuri.org/")
        String customerEmailAddress,
        @WebParam(name = "originalIPAddress", targetNamespace = "http://tempuri.org/")
        String originalIPAddress,
        @WebParam(name = "groupID", targetNamespace = "http://tempuri.org/")
        int groupID,
        @WebParam(name = "serviceID", targetNamespace = "http://tempuri.org/")
        int serviceID,
        @WebParam(name = "privateLabelID", targetNamespace = "http://tempuri.org/")
        int privateLabelID,
        @WebParam(name = "shopperID", targetNamespace = "http://tempuri.org/")
        String shopperID,
        @WebParam(name = "createdBy", targetNamespace = "http://tempuri.org/")
        String createdBy);

    /**
     * 
     * @param note
     * @param originalIPAddress
     * @param privateLabelID
     * @param createdBy
     * @param subject
     * @param customerEmailAddress
     * @param shopperID
     * @param groupID
     * @param incidentType
     * @param subscriberID
     * @param serviceID
     * @return
     *     returns long
     */
    @WebMethod(operationName = "CreateIncidentInIRISByType", action = "http://tempuri.org/CreateIncidentInIRISByType")
    @WebResult(name = "CreateIncidentInIRISByTypeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreateIncidentInIRISByType", targetNamespace = "http://tempuri.org/", className = "irisClient.CreateIncidentInIRISByType")
    @ResponseWrapper(localName = "CreateIncidentInIRISByTypeResponse", targetNamespace = "http://tempuri.org/", className = "irisClient.CreateIncidentInIRISByTypeResponse")
    public long createIncidentInIRISByType(
        @WebParam(name = "subscriberID", targetNamespace = "http://tempuri.org/")
        int subscriberID,
        @WebParam(name = "subject", targetNamespace = "http://tempuri.org/")
        String subject,
        @WebParam(name = "Note", targetNamespace = "http://tempuri.org/")
        String note,
        @WebParam(name = "customerEmailAddress", targetNamespace = "http://tempuri.org/")
        String customerEmailAddress,
        @WebParam(name = "originalIPAddress", targetNamespace = "http://tempuri.org/")
        String originalIPAddress,
        @WebParam(name = "groupID", targetNamespace = "http://tempuri.org/")
        int groupID,
        @WebParam(name = "serviceID", targetNamespace = "http://tempuri.org/")
        int serviceID,
        @WebParam(name = "privateLabelID", targetNamespace = "http://tempuri.org/")
        int privateLabelID,
        @WebParam(name = "shopperID", targetNamespace = "http://tempuri.org/")
        String shopperID,
        @WebParam(name = "createdBy", targetNamespace = "http://tempuri.org/")
        String createdBy,
        @WebParam(name = "incidentType", targetNamespace = "http://tempuri.org/")
        int incidentType);

    /**
     * 
     * @param note
     * @param originalIPAddress
     * @param privateLabelID
     * @param createdBy
     * @param subject
     * @param customerEmailAddress
     * @param shopperID
     * @param groupID
     * @param subscriberID
     * @param employeeID
     * @param serviceID
     * @return
     *     returns long
     */
    @WebMethod(operationName = "CreateIncidentInIRISByEmployee", action = "http://tempuri.org/CreateIncidentInIRISByEmployee")
    @WebResult(name = "CreateIncidentInIRISByEmployeeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreateIncidentInIRISByEmployee", targetNamespace = "http://tempuri.org/", className = "irisClient.CreateIncidentInIRISByEmployee")
    @ResponseWrapper(localName = "CreateIncidentInIRISByEmployeeResponse", targetNamespace = "http://tempuri.org/", className = "irisClient.CreateIncidentInIRISByEmployeeResponse")
    public long createIncidentInIRISByEmployee(
        @WebParam(name = "subscriberID", targetNamespace = "http://tempuri.org/")
        int subscriberID,
        @WebParam(name = "subject", targetNamespace = "http://tempuri.org/")
        String subject,
        @WebParam(name = "Note", targetNamespace = "http://tempuri.org/")
        String note,
        @WebParam(name = "customerEmailAddress", targetNamespace = "http://tempuri.org/")
        String customerEmailAddress,
        @WebParam(name = "originalIPAddress", targetNamespace = "http://tempuri.org/")
        String originalIPAddress,
        @WebParam(name = "groupID", targetNamespace = "http://tempuri.org/")
        int groupID,
        @WebParam(name = "serviceID", targetNamespace = "http://tempuri.org/")
        int serviceID,
        @WebParam(name = "privateLabelID", targetNamespace = "http://tempuri.org/")
        int privateLabelID,
        @WebParam(name = "shopperID", targetNamespace = "http://tempuri.org/")
        String shopperID,
        @WebParam(name = "createdBy", targetNamespace = "http://tempuri.org/")
        String createdBy,
        @WebParam(name = "employeeID", targetNamespace = "http://tempuri.org/")
        int employeeID);

    /**
     * 
     * @param input
     * @return
     *     returns long
     */
    @WebMethod(operationName = "CreateIrisIncident", action = "http://tempuri.org/CreateIrisIncident")
    @WebResult(name = "CreateIrisIncidentResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreateIrisIncident", targetNamespace = "http://tempuri.org/", className = "irisClient.CreateIrisIncident")
    @ResponseWrapper(localName = "CreateIrisIncidentResponse", targetNamespace = "http://tempuri.org/", className = "irisClient.CreateIrisIncidentResponse")
    public long createIrisIncident(
        @WebParam(name = "input", targetNamespace = "http://tempuri.org/")
        CreateIncidentInput input);

    /**
     * 
     * @param note
     * @param originalIPAddress
     * @param privateLabelID
     * @param subject
     * @param customerEmailAddress
     * @param shopperID
     * @param groupID
     * @param incidentType
     * @param subscriberID
     * @param employeeID
     * @param priority
     * @param createdBy
     * @param serviceID
     * @return
     *     returns long
     */
    @WebMethod(operationName = "CreateIncidentInIRISByPriority", action = "http://tempuri.org/CreateIncidentInIRISByPriority")
    @WebResult(name = "CreateIncidentInIRISByPriorityResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreateIncidentInIRISByPriority", targetNamespace = "http://tempuri.org/", className = "irisClient.CreateIncidentInIRISByPriority")
    @ResponseWrapper(localName = "CreateIncidentInIRISByPriorityResponse", targetNamespace = "http://tempuri.org/", className = "irisClient.CreateIncidentInIRISByPriorityResponse")
    public long createIncidentInIRISByPriority(
        @WebParam(name = "subscriberID", targetNamespace = "http://tempuri.org/")
        int subscriberID,
        @WebParam(name = "subject", targetNamespace = "http://tempuri.org/")
        String subject,
        @WebParam(name = "Note", targetNamespace = "http://tempuri.org/")
        String note,
        @WebParam(name = "customerEmailAddress", targetNamespace = "http://tempuri.org/")
        String customerEmailAddress,
        @WebParam(name = "originalIPAddress", targetNamespace = "http://tempuri.org/")
        String originalIPAddress,
        @WebParam(name = "groupID", targetNamespace = "http://tempuri.org/")
        int groupID,
        @WebParam(name = "serviceID", targetNamespace = "http://tempuri.org/")
        int serviceID,
        @WebParam(name = "privateLabelID", targetNamespace = "http://tempuri.org/")
        int privateLabelID,
        @WebParam(name = "shopperID", targetNamespace = "http://tempuri.org/")
        String shopperID,
        @WebParam(name = "createdBy", targetNamespace = "http://tempuri.org/")
        String createdBy,
        @WebParam(name = "incidentType", targetNamespace = "http://tempuri.org/")
        int incidentType,
        @WebParam(name = "employeeID", targetNamespace = "http://tempuri.org/")
        int employeeID,
        @WebParam(name = "priority", targetNamespace = "http://tempuri.org/")
        int priority);

    /**
     * 
     * @param note
     * @param originalIPAddress
     * @param createdBy
     * @param privateLabelID
     * @param subject
     * @param customerEmailAddress
     * @param shopperID
     * @param subscriberID
     * @return
     *     returns long
     */
    @WebMethod(operationName = "CreateQuickIncidentinIRIS", action = "http://tempuri.org/CreateQuickIncidentinIRIS")
    @WebResult(name = "CreateQuickIncidentinIRISResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreateQuickIncidentinIRIS", targetNamespace = "http://tempuri.org/", className = "irisClient.CreateQuickIncidentinIRIS")
    @ResponseWrapper(localName = "CreateQuickIncidentinIRISResponse", targetNamespace = "http://tempuri.org/", className = "irisClient.CreateQuickIncidentinIRISResponse")
    public long createQuickIncidentinIRIS(
        @WebParam(name = "subscriberID", targetNamespace = "http://tempuri.org/")
        int subscriberID,
        @WebParam(name = "subject", targetNamespace = "http://tempuri.org/")
        String subject,
        @WebParam(name = "Note", targetNamespace = "http://tempuri.org/")
        String note,
        @WebParam(name = "customerEmailAddress", targetNamespace = "http://tempuri.org/")
        String customerEmailAddress,
        @WebParam(name = "originalIPAddress", targetNamespace = "http://tempuri.org/")
        String originalIPAddress,
        @WebParam(name = "createdBy", targetNamespace = "http://tempuri.org/")
        String createdBy,
        @WebParam(name = "privateLabelID", targetNamespace = "http://tempuri.org/")
        int privateLabelID,
        @WebParam(name = "shopperID", targetNamespace = "http://tempuri.org/")
        String shopperID);

    /**
     * 
     * @param subscriberID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetOfferingsListBySubscriberID", action = "http://tempuri.org/GetOfferingsListBySubscriberID")
    @WebResult(name = "GetOfferingsListBySubscriberIDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetOfferingsListBySubscriberID", targetNamespace = "http://tempuri.org/", className = "irisClient.GetOfferingsListBySubscriberID")
    @ResponseWrapper(localName = "GetOfferingsListBySubscriberIDResponse", targetNamespace = "http://tempuri.org/", className = "irisClient.GetOfferingsListBySubscriberIDResponse")
    public String getOfferingsListBySubscriberID(
        @WebParam(name = "subscriberID", targetNamespace = "http://tempuri.org/")
        int subscriberID);

    /**
     * 
     * @param groupID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDashboardReportByGroup", action = "http://tempuri.org/GetDashboardReportByGroup")
    @WebResult(name = "GetDashboardReportByGroupResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetDashboardReportByGroup", targetNamespace = "http://tempuri.org/", className = "irisClient.GetDashboardReportByGroup")
    @ResponseWrapper(localName = "GetDashboardReportByGroupResponse", targetNamespace = "http://tempuri.org/", className = "irisClient.GetDashboardReportByGroupResponse")
    public String getDashboardReportByGroup(
        @WebParam(name = "groupID", targetNamespace = "http://tempuri.org/")
        int groupID);

    /**
     * 
     * @param groupId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDashboardReportByGroupWithCategories", action = "http://tempuri.org/GetDashboardReportByGroupWithCategories")
    @WebResult(name = "GetDashboardReportByGroupWithCategoriesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetDashboardReportByGroupWithCategories", targetNamespace = "http://tempuri.org/", className = "irisClient.GetDashboardReportByGroupWithCategories")
    @ResponseWrapper(localName = "GetDashboardReportByGroupWithCategoriesResponse", targetNamespace = "http://tempuri.org/", className = "irisClient.GetDashboardReportByGroupWithCategoriesResponse")
    public String getDashboardReportByGroupWithCategories(
        @WebParam(name = "groupId", targetNamespace = "http://tempuri.org/")
        int groupId);

    /**
     * 
     * @param endDate
     * @param shopperId
     * @param startDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetIncidentsByShopperIdAndDateRange", action = "http://tempuri.org/GetIncidentsByShopperIdAndDateRange")
    @WebResult(name = "GetIncidentsByShopperIdAndDateRangeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetIncidentsByShopperIdAndDateRange", targetNamespace = "http://tempuri.org/", className = "irisClient.GetIncidentsByShopperIdAndDateRange")
    @ResponseWrapper(localName = "GetIncidentsByShopperIdAndDateRangeResponse", targetNamespace = "http://tempuri.org/", className = "irisClient.GetIncidentsByShopperIdAndDateRangeResponse")
    public String getIncidentsByShopperIdAndDateRange(
        @WebParam(name = "shopperId", targetNamespace = "http://tempuri.org/")
        String shopperId,
        @WebParam(name = "startDate", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar endDate);

    /**
     * 
     * @param noteId
     * @param incidentId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetIncidentCustomerNotes", action = "http://tempuri.org/GetIncidentCustomerNotes")
    @WebResult(name = "GetIncidentCustomerNotesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetIncidentCustomerNotes", targetNamespace = "http://tempuri.org/", className = "irisClient.GetIncidentCustomerNotes")
    @ResponseWrapper(localName = "GetIncidentCustomerNotesResponse", targetNamespace = "http://tempuri.org/", className = "irisClient.GetIncidentCustomerNotesResponse")
    public String getIncidentCustomerNotes(
        @WebParam(name = "incidentId", targetNamespace = "http://tempuri.org/")
        long incidentId,
        @WebParam(name = "noteId", targetNamespace = "http://tempuri.org/")
        int noteId);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetServiceGroupLookUp", action = "http://tempuri.org/GetServiceGroupLookUp")
    @WebResult(name = "GetServiceGroupLookUpResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetServiceGroupLookUp", targetNamespace = "http://tempuri.org/", className = "irisClient.GetServiceGroupLookUp")
    @ResponseWrapper(localName = "GetServiceGroupLookUpResponse", targetNamespace = "http://tempuri.org/", className = "irisClient.GetServiceGroupLookUpResponse")
    public String getServiceGroupLookUp();

    /**
     * 
     * @param note
     * @param ntLogin
     * @param incidentID
     * @return
     *     returns int
     */
    @WebMethod(operationName = "AddIncidentNote", action = "http://tempuri.org/AddIncidentNote")
    @WebResult(name = "AddIncidentNoteResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddIncidentNote", targetNamespace = "http://tempuri.org/", className = "irisClient.AddIncidentNote")
    @ResponseWrapper(localName = "AddIncidentNoteResponse", targetNamespace = "http://tempuri.org/", className = "irisClient.AddIncidentNoteResponse")
    public int addIncidentNote(
        @WebParam(name = "incidentID", targetNamespace = "http://tempuri.org/")
        long incidentID,
        @WebParam(name = "Note", targetNamespace = "http://tempuri.org/")
        String note,
        @WebParam(name = "NTLogin", targetNamespace = "http://tempuri.org/")
        String ntLogin);

    /**
     * This method is called only by the mobile app team.
     * 
     * @param note
     * @param ntLogin
     * @param noteTypeId
     * @param incidentId
     * @return
     *     returns int
     */
    @WebMethod(operationName = "AddIncidentNoteByNoteTypeId", action = "http://tempuri.org/AddIncidentNoteByNoteTypeId")
    @WebResult(name = "AddIncidentNoteByNoteTypeIdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddIncidentNoteByNoteTypeId", targetNamespace = "http://tempuri.org/", className = "irisClient.AddIncidentNoteByNoteTypeId")
    @ResponseWrapper(localName = "AddIncidentNoteByNoteTypeIdResponse", targetNamespace = "http://tempuri.org/", className = "irisClient.AddIncidentNoteByNoteTypeIdResponse")
    public int addIncidentNoteByNoteTypeId(
        @WebParam(name = "incidentId", targetNamespace = "http://tempuri.org/")
        long incidentId,
        @WebParam(name = "note", targetNamespace = "http://tempuri.org/")
        String note,
        @WebParam(name = "NTLogin", targetNamespace = "http://tempuri.org/")
        String ntLogin,
        @WebParam(name = "noteTypeId", targetNamespace = "http://tempuri.org/")
        int noteTypeId);

    /**
     * 
     */
    @WebMethod(operationName = "ResetStaticData", action = "http://tempuri.org/ResetStaticData")
    @RequestWrapper(localName = "ResetStaticData", targetNamespace = "http://tempuri.org/", className = "irisClient.ResetStaticData")
    @ResponseWrapper(localName = "ResetStaticDataResponse", targetNamespace = "http://tempuri.org/", className = "irisClient.ResetStaticDataResponse")
    public void resetStaticData();

    /**
     * 
     * @param note
     * @param originalIPAddress
     * @param privateLabelID
     * @param createdBy
     * @param subject
     * @param customerEmailAddress
     * @param shopperID
     * @param groupID
     * @param subscriberID
     * @param employeeID
     * @param serviceID
     * @return
     *     returns long
     */
    @WebMethod(operationName = "QuickResolveIncident", action = "http://tempuri.org/QuickResolveIncident")
    @WebResult(name = "QuickResolveIncidentResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "QuickResolveIncident", targetNamespace = "http://tempuri.org/", className = "irisClient.QuickResolveIncident")
    @ResponseWrapper(localName = "QuickResolveIncidentResponse", targetNamespace = "http://tempuri.org/", className = "irisClient.QuickResolveIncidentResponse")
    public long quickResolveIncident(
        @WebParam(name = "subscriberID", targetNamespace = "http://tempuri.org/")
        int subscriberID,
        @WebParam(name = "subject", targetNamespace = "http://tempuri.org/")
        String subject,
        @WebParam(name = "note", targetNamespace = "http://tempuri.org/")
        String note,
        @WebParam(name = "customerEmailAddress", targetNamespace = "http://tempuri.org/")
        String customerEmailAddress,
        @WebParam(name = "originalIPAddress", targetNamespace = "http://tempuri.org/")
        String originalIPAddress,
        @WebParam(name = "groupID", targetNamespace = "http://tempuri.org/")
        int groupID,
        @WebParam(name = "serviceID", targetNamespace = "http://tempuri.org/")
        int serviceID,
        @WebParam(name = "privateLabelID", targetNamespace = "http://tempuri.org/")
        int privateLabelID,
        @WebParam(name = "shopperID", targetNamespace = "http://tempuri.org/")
        String shopperID,
        @WebParam(name = "createdBy", targetNamespace = "http://tempuri.org/")
        String createdBy,
        @WebParam(name = "employeeID", targetNamespace = "http://tempuri.org/")
        int employeeID);

    /**
     * 
     * @param employeeId
     * @param incidentId
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "QuickCloseIncident", action = "http://tempuri.org/QuickCloseIncident")
    @WebResult(name = "QuickCloseIncidentResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "QuickCloseIncident", targetNamespace = "http://tempuri.org/", className = "irisClient.QuickCloseIncident")
    @ResponseWrapper(localName = "QuickCloseIncidentResponse", targetNamespace = "http://tempuri.org/", className = "irisClient.QuickCloseIncidentResponse")
    public boolean quickCloseIncident(
        @WebParam(name = "incidentId", targetNamespace = "http://tempuri.org/")
        long incidentId,
        @WebParam(name = "employeeId", targetNamespace = "http://tempuri.org/")
        int employeeId);

    /**
     * 
     * @param updatedBy
     * @param newPriority
     * @param incidentID
     * @return
     *     returns int
     */
    @WebMethod(operationName = "UpdatePriority", action = "http://tempuri.org/UpdatePriority")
    @WebResult(name = "UpdatePriorityResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdatePriority", targetNamespace = "http://tempuri.org/", className = "irisClient.UpdatePriority")
    @ResponseWrapper(localName = "UpdatePriorityResponse", targetNamespace = "http://tempuri.org/", className = "irisClient.UpdatePriorityResponse")
    public int updatePriority(
        @WebParam(name = "incidentID", targetNamespace = "http://tempuri.org/")
        long incidentID,
        @WebParam(name = "updatedBy", targetNamespace = "http://tempuri.org/")
        String updatedBy,
        @WebParam(name = "newPriority", targetNamespace = "http://tempuri.org/")
        int newPriority);

    /**
     * 
     * @return returns
     *         irisClient.GetAllPrioritiesResponse.GetAllPrioritiesResult
     */
    @WebMethod(operationName = "GetAllPriorities", action = "http://tempuri.org/GetAllPriorities")
    @WebResult(name = "GetAllPrioritiesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAllPriorities", targetNamespace = "http://tempuri.org/", className = "irisClient.GetAllPriorities")
    @ResponseWrapper(localName = "GetAllPrioritiesResponse",
            targetNamespace = "http://tempuri.org/",
            className = "irisClient.GetAllPrioritiesResponse")
    public GetAllPrioritiesResponse.GetAllPrioritiesResult getAllPriorities();

    /**
     * 
     * @param documentTypeID
     * @return returns
     *         irisClient.GetPrioritiesByDocumentTypeResponse.GetPrioritiesByDocumentTypeResult
     */
    @WebMethod(operationName = "GetPrioritiesByDocumentType", action = "http://tempuri.org/GetPrioritiesByDocumentType")
    @WebResult(name = "GetPrioritiesByDocumentTypeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPrioritiesByDocumentType",
            targetNamespace = "http://tempuri.org/",
            className = "irisClient.GetPrioritiesByDocumentType")
    @ResponseWrapper(localName = "GetPrioritiesByDocumentTypeResponse",
            targetNamespace = "http://tempuri.org/",
            className = "irisClient.GetPrioritiesByDocumentTypeResponse")
    public GetPrioritiesByDocumentTypeResponse.GetPrioritiesByDocumentTypeResult getPrioritiesByDocumentType(
            @WebParam(name = "documentTypeID", targetNamespace = "http://tempuri.org/") int documentTypeID);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetVersion", action = "http://tempuri.org/GetVersion")
    @WebResult(name = "GetVersionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetVersion", targetNamespace = "http://tempuri.org/", className = "irisClient.GetVersion")
    @ResponseWrapper(localName = "GetVersionResponse", targetNamespace = "http://tempuri.org/", className = "irisClient.GetVersionResponse")
    public String getVersion();

    /**
     * The SubscriberDescription in the input can be email address or the name of the subscriber.
     * 
     * @param input
     * @return
     *     returns irisClient.SubscriberInfo
     */
    @WebMethod(operationName = "GetSubscriberByCriteria", action = "http://tempuri.org/GetSubscriberByCriteria")
    @WebResult(name = "GetSubscriberByCriteriaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSubscriberByCriteria", targetNamespace = "http://tempuri.org/", className = "irisClient.GetSubscriberByCriteria")
    @ResponseWrapper(localName = "GetSubscriberByCriteriaResponse", targetNamespace = "http://tempuri.org/", className = "irisClient.GetSubscriberByCriteriaResponse")
    public SubscriberInfo getSubscriberByCriteria(
        @WebParam(name = "input", targetNamespace = "http://tempuri.org/")
        SearchSubscriberInput input);

    /**
     * 
     * @param input
     * @return
     *     returns irisClient.IncidentInfo
     */
    @WebMethod(operationName = "GetIncidentInfoByIncidentId", action = "http://tempuri.org/GetIncidentInfoByIncidentId")
    @WebResult(name = "GetIncidentInfoByIncidentIdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetIncidentInfoByIncidentId", targetNamespace = "http://tempuri.org/", className = "irisClient.GetIncidentInfoByIncidentId")
    @ResponseWrapper(localName = "GetIncidentInfoByIncidentIdResponse", targetNamespace = "http://tempuri.org/", className = "irisClient.GetIncidentInfoByIncidentIdResponse")
    public IncidentInfo getIncidentInfoByIncidentId(
        @WebParam(name = "input", targetNamespace = "http://tempuri.org/")
        IncidentInput input);

}
