package com.godaddy.vps4.orchestration;

import com.godaddy.vps4.orchestration.dns.Vps4CreateDnsPtrRecord;
import com.godaddy.vps4.orchestration.mailrelay.Vps4SetMailRelayQuota;
import com.godaddy.vps4.orchestration.messaging.SendFailoverCompletedEmail;
import com.godaddy.vps4.orchestration.messaging.SendScheduledPatchingEmail;
import com.godaddy.vps4.orchestration.messaging.SendSystemDownFailoverEmail;
import com.godaddy.vps4.orchestration.messaging.SendUnexpectedButScheduledMaintenanceEmail;
import com.godaddy.vps4.orchestration.messaging.WaitForMessageComplete;
import com.godaddy.vps4.orchestration.monitoring.DeletePanoptaCustomer;
import com.godaddy.vps4.orchestration.monitoring.RemoveNodePingMonitoring;
import com.godaddy.vps4.orchestration.monitoring.RemovePanoptaMonitoring;
import com.godaddy.vps4.orchestration.monitoring.Vps4RemoveMonitoring;
import com.godaddy.vps4.orchestration.panopta.PausePanoptaMonitoring;
import com.godaddy.vps4.orchestration.panopta.ResumePanoptaMonitoring;
import com.godaddy.vps4.orchestration.snapshot.Vps4DestroySnapshot;
import com.godaddy.vps4.orchestration.snapshot.Vps4SnapshotVm;
import com.godaddy.vps4.orchestration.sysadmin.Vps4AddSupportUser;
import com.godaddy.vps4.orchestration.sysadmin.Vps4RemoveSupportUser;
import com.godaddy.vps4.orchestration.sysadmin.Vps4SetHostname;
import com.godaddy.vps4.orchestration.sysadmin.Vps4SetPassword;
import com.godaddy.vps4.orchestration.sysadmin.Vps4ToggleAdmin;
import com.godaddy.vps4.orchestration.vm.UnlicenseControlPanel;
import com.godaddy.vps4.orchestration.vm.Vps4AddIpAddress;
import com.godaddy.vps4.orchestration.vm.Vps4CancelAction;
import com.godaddy.vps4.orchestration.vm.Vps4DeleteAllScheduledJobsForVm;
import com.godaddy.vps4.orchestration.vm.Vps4DestroyDedicated;
import com.godaddy.vps4.orchestration.vm.Vps4DestroyIpAddress;
import com.godaddy.vps4.orchestration.vm.Vps4DestroyIpAddressAction;
import com.godaddy.vps4.orchestration.vm.Vps4DestroyVm;
import com.godaddy.vps4.orchestration.vm.Vps4EndRescue;
import com.godaddy.vps4.orchestration.vm.Vps4PlanChange;
import com.godaddy.vps4.orchestration.vm.Vps4RebootDedicated;
import com.godaddy.vps4.orchestration.vm.Vps4RebuildDedicated;
import com.godaddy.vps4.orchestration.vm.Vps4RebuildVm;
import com.godaddy.vps4.orchestration.vm.Vps4RecordScheduledJobForVm;
import com.godaddy.vps4.orchestration.vm.Vps4ReinstateDedServer;
import com.godaddy.vps4.orchestration.vm.Vps4ReinstateServer;
import com.godaddy.vps4.orchestration.vm.Vps4RemoveSupportUsersFromDatabase;
import com.godaddy.vps4.orchestration.vm.Vps4Rescue;
import com.godaddy.vps4.orchestration.vm.Vps4RestartVm;
import com.godaddy.vps4.orchestration.vm.Vps4RestoreVm;
import com.godaddy.vps4.orchestration.vm.Vps4ReviveZombieVm;
import com.godaddy.vps4.orchestration.vm.Vps4StartVm;
import com.godaddy.vps4.orchestration.vm.Vps4StopVm;
import com.godaddy.vps4.orchestration.vm.Vps4SuspendDedServer;
import com.godaddy.vps4.orchestration.vm.Vps4SuspendServer;
import com.godaddy.vps4.orchestration.vm.Vps4TestCommand;
import com.godaddy.vps4.orchestration.vm.Vps4UpgradeVm;
import com.godaddy.vps4.orchestration.vm.provision.Vps4ProvisionDedicated;
import com.godaddy.vps4.orchestration.vm.provision.Vps4ProvisionVm;
import com.google.inject.AbstractModule;

public class Vps4CommandModule extends AbstractModule {

    @Override
    public void configure() {
        bind(Vps4ProvisionVm.class);
        bind(Vps4ProvisionDedicated.class);
        bind(Vps4ToggleAdmin.class);
        bind(Vps4SetPassword.class);
        bind(Vps4SetHostname.class);
        bind(Vps4TestCommand.class);
        bind(Vps4DestroyVm.class);
        bind(Vps4DestroyDedicated.class);
        bind(Vps4StartVm.class);
        bind(Vps4StopVm.class);
        bind(Vps4RestartVm.class);
        bind(Vps4RebootDedicated.class);
        bind(Vps4DestroyIpAddress.class);
        bind(Vps4DestroyIpAddressAction.class);
        bind(Vps4AddIpAddress.class);
        bind(Vps4AddSupportUser.class);
        bind(Vps4RemoveSupportUser.class);
        bind(Vps4SnapshotVm.class);
        bind(Vps4DestroySnapshot.class);
        bind(Vps4SetMailRelayQuota.class);
        bind(Vps4RestoreVm.class);
        bind(Vps4RebuildVm.class);
        bind(Vps4RebuildDedicated.class);
        bind(Vps4PlanChange.class);
        bind(Vps4ReviveZombieVm.class);
        bind(Vps4DeleteAllScheduledJobsForVm.class);
        bind(Vps4RecordScheduledJobForVm.class);
        bind(Vps4RemoveSupportUsersFromDatabase.class);
        bind(UnlicenseControlPanel.class);
        bind(SendScheduledPatchingEmail.class);
        bind(SendUnexpectedButScheduledMaintenanceEmail.class);
        bind(SendSystemDownFailoverEmail.class);
        bind(SendFailoverCompletedEmail.class);
        bind(WaitForMessageComplete.class);
        bind(Vps4CancelAction.class);
        bind(Vps4UpgradeVm.class);
        bind(Vps4EndRescue.class);
        bind(Vps4Rescue.class);
        bind(Vps4SuspendServer.class);
        bind(Vps4SuspendDedServer.class);
        bind(Vps4ReinstateServer.class);
        bind(Vps4ReinstateDedServer.class);
        bind(Vps4CreateDnsPtrRecord.class);
        bind(PausePanoptaMonitoring.class);
        bind(ResumePanoptaMonitoring.class);
        bind(Vps4RemoveMonitoring.class);
        bind(RemovePanoptaMonitoring.class);
        bind(RemoveNodePingMonitoring.class);
        bind(DeletePanoptaCustomer.class);
    }
}
