import hudson.model.*
import groovy.transform.Field

@Field def VPS4_VERSION
pipeline {
    agent { label "vps4-test-slave" }
    options { 
        skipStagesAfterUnstable()
        timestamps()
        disableConcurrentBuilds()
        skipDefaultCheckout() 
    }
    stages {
        stage ("PR Verification")
        {
            when {
                not {
                    branch 'Master'
                }
            }
            steps{
                build job: 'pr-validation', parameters: [string(name: 'branch', value: "${env.BRANCH_NAME}")]
            }
        }
        stage ("Build Master and Deploy to Test and Stage")
        {
            when {
                    branch 'Master'
            }
            steps {
                build job: 'test-stage'
            }
        }
    }
} 