package com.godaddy.vps4.web;

import com.godaddy.vps4.web.action.ActionResource;
import com.godaddy.vps4.web.appmonitors.VmActionsMonitorResource;
import com.godaddy.vps4.web.audit.AuditHfsVmResource;
import com.godaddy.vps4.web.cache.CacheResource;
import com.godaddy.vps4.web.console.ConsoleResource;
import com.godaddy.vps4.web.controlPanel.cpanel.CPanelResource;
import com.godaddy.vps4.web.controlPanel.plesk.PleskResource;
import com.godaddy.vps4.web.credit.CreditProdMetaResource;
import com.godaddy.vps4.web.credit.CreditResource;
import com.godaddy.vps4.web.customNotes.CustomNotesResource;
import com.godaddy.vps4.web.dns.ActionCommandHelper;
import com.godaddy.vps4.web.dns.DnsResource;
import com.godaddy.vps4.web.dns.ObjectMapperProvider;
import com.godaddy.vps4.web.dns.ReverseDnsLookup;
import com.godaddy.vps4.web.entitlementAction.ChatterboxResource;
import com.godaddy.vps4.web.featureFlag.ConfigFeatureMaskModule;
import com.godaddy.vps4.web.cdn.CdnResource;
import com.godaddy.vps4.web.intervention.InterventionResource;
import com.godaddy.vps4.web.mailrelay.VmMailRelayResource;
import com.godaddy.vps4.web.messaging.VmMessagingResource;
import com.godaddy.vps4.web.monitoring.VmAddMonitoringResource;
import com.godaddy.vps4.web.monitoring.VmAlertResource;
import com.godaddy.vps4.web.monitoring.VmDomainMonitoringResource;
import com.godaddy.vps4.web.monitoring.VmMonitoringResource;
import com.godaddy.vps4.web.monitoring.VmOutageResource;
import com.godaddy.vps4.web.network.NetworkResource;
import com.godaddy.vps4.web.notification.NotificationsResource;
import com.godaddy.vps4.web.ohbackup.OhBackupResource;
import com.godaddy.vps4.web.open.AvailabilityResource;
import com.godaddy.vps4.web.open.UnavailablePackagesResource;
import com.godaddy.vps4.web.plan.PlanResource;
import com.godaddy.vps4.web.security.Vps4ContainerRequestFilterModule;
import com.godaddy.vps4.web.sysadmin.SysAdminResource;
import com.godaddy.vps4.web.ticketing.VmJsdTicketingResource;
import com.godaddy.vps4.web.validator.ValidatorResource;
import com.godaddy.vps4.web.vm.ImageResource;
import com.godaddy.vps4.web.vm.InventoryResource;
import com.godaddy.vps4.web.vm.OrphanResource;
import com.godaddy.vps4.web.vm.PlatformMigrationResource;
import com.godaddy.vps4.web.vm.ServerUsageStatsResource;
import com.godaddy.vps4.web.vm.SnapshotScheduleResource;
import com.godaddy.vps4.web.vm.UserResource;
import com.godaddy.vps4.web.vm.VmActionResource;
import com.godaddy.vps4.web.vm.VmBootscriptResource;
import com.godaddy.vps4.web.vm.VmDetailsResource;
import com.godaddy.vps4.web.vm.VmFlavorResource;
import com.godaddy.vps4.web.vm.VmImportResource;
import com.godaddy.vps4.web.vm.VmIntentResource;
import com.godaddy.vps4.web.vm.VmNotificationResource;
import com.godaddy.vps4.web.vm.VmNydusAckResource;
import com.godaddy.vps4.web.vm.VmPatchResource;
import com.godaddy.vps4.web.vm.VmPlanResource;
import com.godaddy.vps4.web.vm.VmRebuildResource;
import com.godaddy.vps4.web.vm.VmRescueResource;
import com.godaddy.vps4.web.vm.VmResource;
import com.godaddy.vps4.web.vm.VmRestoreResource;
import com.godaddy.vps4.web.vm.VmShopperMergeResource;
import com.godaddy.vps4.web.vm.VmSnapshotActionResource;
import com.godaddy.vps4.web.vm.VmSnapshotResource;
import com.godaddy.vps4.web.vm.VmSupportUserResource;
import com.godaddy.vps4.web.vm.VmSuspendReinstateResource;
import com.godaddy.vps4.web.vm.VmSyncStatusResource;
import com.godaddy.vps4.web.vm.VmTroubleshootResource;
import com.godaddy.vps4.web.vm.VmUpgradeResource;
import com.godaddy.vps4.web.vm.VmZombieResource;
import com.godaddy.vps4.web.vm.WinexeResource;
import com.google.inject.AbstractModule;

import gdg.hfs.orchestration.web.CommandsResource;
import gdg.hfs.orchestration.web.CommandsViewResource;

public class WebModule extends AbstractModule {

    @Override
    public void configure() {
        bind(StatusResource.class);

        bind(VmResource.class);
        bind(VmRestoreResource.class);
        bind(VmRebuildResource.class);
        bind(VmActionResource.class);
        bind(VmFlavorResource.class);
        bind(VmPatchResource.class);
        bind(VmMailRelayResource.class);
        bind(VmMonitoringResource.class);
        bind(VmSupportUserResource.class);
        bind(VmZombieResource.class);
        bind(VmTroubleshootResource.class);
        bind(ValidatorResource.class);
        bind(CPanelResource.class);
        bind(PleskResource.class);
        bind(SysAdminResource.class);
        bind(UserResource.class);
        bind(CreditResource.class);
        bind(CreditProdMetaResource.class);
        bind(ImageResource.class);
        bind(ServerUsageStatsResource.class);
        bind(CacheResource.class);
        bind(VmSnapshotResource.class);
        bind(SnapshotScheduleResource.class);
        bind(NetworkResource.class);
        bind(VmSnapshotActionResource.class);
        bind(Vps4ExceptionMapper.class);
        bind(VmActionsMonitorResource.class);
        bind(ConsoleResource.class);
        bind(VmMessagingResource.class);
        bind(VmUpgradeResource.class);
        bind(ActionResource.class);
        bind(VmSuspendReinstateResource.class);
        bind(OrphanResource.class);
        bind(PlanResource.class);
        bind(AuditHfsVmResource.class);
        bind(VmRescueResource.class);
        bind(VmShopperMergeResource.class);
        bind(ObjectMapperProvider.class); // do not remove - Guice requires explicit binding
        bind(ActionCommandHelper.class);
        bind(ReverseDnsLookup.class);
        bind(DnsResource.class);
        bind(VmAlertResource.class);
        bind(VmOutageResource.class);
        bind(VmDetailsResource.class);
        bind(InventoryResource.class);
        bind(VmAddMonitoringResource.class);
        bind(VmNydusAckResource.class);
        bind(VmSyncStatusResource.class);
        bind(VmImportResource.class);
        bind(NotificationsResource.class);
        bind(VmNotificationResource.class);
        bind(WinexeResource.class);
        bind(VmPlanResource.class);
        bind(CustomNotesResource.class);
        bind(VmDomainMonitoringResource.class);
        bind(VmJsdTicketingResource.class);
        bind(OhBackupResource.class);
        bind(PlatformMigrationResource.class);
        bind(VmBootscriptResource.class);
        bind(InterventionResource.class);
        bind(CdnResource.class);
        bind(ChatterboxResource.class);
        bind(VmIntentResource.class);

        bind(CommandsResource.class);
        bind(CommandsViewResource.class);

        bind(AvailabilityResource.class);
        bind(UnavailablePackagesResource.class);

        install(new ActionCancelModule());
        install(new Vps4ContainerRequestFilterModule());
        install(new ConfigFeatureMaskModule());
    }
}
