CREATE TABLE package (
    id SERIAL NOT NULL PRIMARY KEY,
    package_id TEXT NOT NULL,
    tier INTEGER NOT NULL
);

INSERT INTO package (package_id, tier) VALUES
    ('ded4-fully-managed-hdd-linux-cpanel-tier1', 60),
    ('ded4-fully-managed-hdd-linux-cpanel-tier3', 80),
    ('ded4-fully-managed-hdd-linux-cpanel-tier5', 100),
    ('ded4-fully-managed-hdd-linux-cpanel-tier6', 110),
    ('ded4-fully-managed-hdd-linux-plesk-tier1', 60),
    ('ded4-fully-managed-hdd-linux-plesk-tier3', 80),
    ('ded4-fully-managed-hdd-linux-plesk-tier5', 100),
    ('ded4-fully-managed-hdd-linux-plesk-tier6', 110),
    ('ded4-fully-managed-ssd-linux-cpanel-tier1', 120),
    ('ded4-fully-managed-ssd-linux-cpanel-tier3', 140),
    ('ded4-fully-managed-ssd-linux-cpanel-tier5', 160),
    ('ded4-fully-managed-ssd-linux-cpanel-tier6', 170),
    ('ded4-fully-managed-ssd-linux-plesk-tier1', 120),
    ('ded4-fully-managed-ssd-linux-plesk-tier3', 140),
    ('ded4-fully-managed-ssd-linux-plesk-tier5', 160),
    ('ded4-fully-managed-ssd-linux-plesk-tier6', 170),
    ('ded4-managed-hdd-linux-cpanel-tier1', 60),
    ('ded4-managed-hdd-linux-cpanel-tier3', 80),
    ('ded4-managed-hdd-linux-cpanel-tier5', 100),
    ('ded4-managed-hdd-linux-cpanel-tier6', 110),
    ('ded4-managed-hdd-linux-plesk-tier1', 60),
    ('ded4-managed-hdd-linux-plesk-tier3', 80),
    ('ded4-managed-hdd-linux-plesk-tier5', 100),
    ('ded4-managed-hdd-linux-plesk-tier6', 110),
    ('ded4-managed-ssd-linux-cpanel-tier1', 120),
    ('ded4-managed-ssd-linux-cpanel-tier3', 140),
    ('ded4-managed-ssd-linux-cpanel-tier5', 160),
    ('ded4-managed-ssd-linux-cpanel-tier6', 170),
    ('ded4-managed-ssd-linux-plesk-tier1', 120),
    ('ded4-managed-ssd-linux-plesk-tier3', 140),
    ('ded4-managed-ssd-linux-plesk-tier5', 160),
    ('ded4-managed-ssd-linux-plesk-tier6', 170),
    ('ded4-selfmanaged-hdd-linux-tier1', 60),
    ('ded4-selfmanaged-hdd-linux-tier3', 80),
    ('ded4-selfmanaged-hdd-linux-tier5', 100),
    ('ded4-selfmanaged-hdd-linux-tier6', 110),
    ('ded4-selfmanaged-hdd-windows-tier1', 60),
    ('ded4-selfmanaged-hdd-windows-tier3', 80),
    ('ded4-selfmanaged-hdd-windows-tier5', 100),
    ('ded4-selfmanaged-hdd-windows-tier6', 110),
    ('ded4-selfmanaged-ssd-linux-tier1', 120),
    ('ded4-selfmanaged-ssd-linux-tier3', 140),
    ('ded4-selfmanaged-ssd-linux-tier5', 160),
    ('ded4-selfmanaged-ssd-linux-tier6', 170),
    ('ded4-selfmanaged-ssd-windows-tier1', 120),
    ('ded4-selfmanaged-ssd-windows-tier3', 140),
    ('ded4-selfmanaged-ssd-windows-tier5', 160),
    ('ded4-selfmanaged-ssd-windows-tier6', 170);
